Repository Mergifyio/browser-extension, pull requests merged in 2025-03, with the labels that each got.

#39 feat: store whether the page is managed by Mergify in a cache
  src/mergify.js
Labels: skip changelog

#38 chore: fix outdated comment
  src/mergify.js
Labels: queued

#40 test: add first unit tests
  .github/workflows/ci.yaml
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/mergify.test.js
  src/mergify.js
Labels: queued

#41 refactor: use `let` instead of `var`
  src/mergify.js
Labels: queued

#42 refactor: check if Mergify section is injected first
  src/mergify.js
Labels: queued

#48 fix: ping right account
  src/mergify.js
Labels: queued

#49 fix: add a better logo for light color mode
  src/mergify.js
Labels: queued

#50 chore: add missing let
  src/mergify.js
Labels: queued

#51 chore: add alias to run jest
  .github/workflows/ci.yaml
  package-lock.json
  package.json
Labels: queued

#52 ci: don't ship __tests__ to browser marketplaces
  Makefile
Labels: queued

#58 ci: add linters
  .github/workflows/ci.yaml
  biome.json
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/mergify.test.js
  src/manifest.json
  src/mergify.js
  src/sendInstallState.js
Labels: queued

#60 feat: add safari build
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .gitignore
  Makefile
Labels: queued, need changelog
